### ISSUE TITLE
Binary loader not working with Donut shellcode

### ISSUE THREAD

**Issue by kyleavery** [optiv/ScareCrow#19]
I am generating shellcode with donut, specifying x64. The CPL loader works as expected, but the binary loader does not:
![output](https://user-images.githubusercontent.com/9327972/127433637-e768f74f-d29a-4d6d-925e-5e57071c2800.png)

The shellcode is being generated from [Atlas](https://github.com/MythicAgents/atlas), a .NET implant, if that makes a difference. Could this be related to https://github.com/optiv/ScareCrow/issues/7?

**Comment by kyleavery** [comment]
This is a stageless payload.

**Comment by Tylous** [comment]
So it shouldn't be related to #7 as the call to shellcode has changed since then. So some obvious questions to ask before we go into the weeds. Is .Net .NET 3.5 and/or 4.0 installed on the box you are launching on? Second is your shellcode trying to run in a thread or run in a separate process? Providing the command and sets you did to generate the shellcode can help me replicate the issue.

**Comment by kyleavery** [comment]
.NET 4.0 is installed on the target endpoint. I believe Donut executes in a new thread. The command used to generate the shellcode is `donut -f 1 -a 2 Atlas.exe` where `-f 1` outputs in raw format and `-a 2` sets the architecture to x64.
The following scenarios were tested:
- Atlas.exe executed on host - Works
- Donut shellcode output ran in DonutTest shellcode runner - Works
- Donut shellcode output ran in ScareCrow CPL loader - Works
- Donut shellcode output ran in ScareCrow binary loader - Fails

**Comment by Tylous** [comment]
So I mean it sounds like it could be something with how the binary is "interpreted"  or the method binary-based loaders use to make the shellcode executable in memory. Binary-based use a technique of taking the string in memory and making it executable, if donut needs extra space to pad it might be overwriting non-writable sections.  Since the DLL-based loaders are working fine (CPL loaders use the same method as the msiexec, wscript, DLL, etc.. to allocate the shellcode on the stack). Would you mind seeing if https://github.com/phra/PEzor or https://github.com/hasherezade/pe_to_shellcode cause the same issue? If you are strapped for time that's fine. CPL and other loaders sound to be working for you so you have that at least. I don't want to delay if you are in a time crunch. Also, I do recommend other loaders over binaries as the other ones can bypass whitelisting pretty well :)

**Comment by kyleavery** [comment]
I'll try those this evening, no time crunch as this is just for a personal project. Totally agree on the loader selection bit, just trying to offer operators as many options as possible.

**Comment by kyleavery** [comment]
So pe_to_shellcode (using runshc64.exe) and PEzor both work, but it holds the process open (implant dies when runshc64.exe or PEzor output binary dies).

**Comment by Tylous** [comment]
Sorry not exactly following what you mean happened?

**Comment by kyleavery** [comment]
Hey sorry, let me explain. The implant calls back and stays connected with both tools (runshc64.exe and PEzor output). I ran both of these from the command line, and in both cases closing the window or pressing ctrl+c killed the agent.

**Comment by Tylous** [comment]
Sorry for the delay, I've been trying to recreate this issue with minimal success. I do think it could be the loader type itself. Since it works fine in DLL/CPL loaders works it could be the specific loader technique as I described above,  the binary loader overwrites some pointers to gain RX privileges without allocating a new buffer and writing the shellcode in there. I will keep looking into it but feel free to reach out to me with more details and I can try to zero on this issue sooner.

**Comment by kyleavery** [comment]
I appreciate the time you've spent, if I have some time this weekend I may look into how Donut is managing memory and provide more info.

**Comment by HuskyHacks** [comment]
@kyleavery @Tylous I'm experiencing this too, agent works when using the regular compiled binary, Donut generates it to shellcode that can run in a custom wrapper, and that works too. But the raw binary output isn't producing the same result when using ScareCrow. Unlike @kyleavery, I can't even get the CPL to work. Attempting to recreate with PEzor as we speak, but in any case my report is basically the same as noted in this ticket

edit: confirmed PEzor agent.bin shellcode -> packed EXE works as expected and check in occurs.

**Comment by vysecurity** [comment]
Just ran a x64 bit shellcode through the EXE, doesn't even run the code.

Cobaltstrike 64 bit bin file.

![image](https://user-images.githubusercontent.com/3596242/128902056-71d27d1b-fc6b-4896-bc19-0a3b2e53ad6b.png)

**Comment by Tylous** [comment]
> @kyleavery @Tylous I'm experiencing this too, agent works when using the regular compiled binary, Donut generates it to shellcode that can run in a custom wrapper, and that works too. But the raw binary output isn't producing the same result when using ScareCrow. Unlike @kyleavery, I can't even get the CPL to work. Attempting to recreate with PEzor as we speak, but in any case my report is basically the same as noted in this ticket
> 
> edit: confirmed PEzor agent.bin shellcode -> packed EXE works as expected and check in occurs.

When you say "raw binary" do you mean something that is not shellcode?

**Comment by kyleavery** [comment]
> When you say "raw binary" do you mean something that is not shellcode?

I believe he is referring to the "binary" output mode of donut, which is shellcode.

**Comment by Tylous** [comment]
Okay well it sounds like the problem occurs syscall.syscall calling the ptr to the donut. I wonder if (given your getting a 0xc0000005 access denied error) it has to do with some added spacing donut needs to expand in memory. I will have to test more.

**Comment by Tylous** [comment]
> Just ran a x64 bit shellcode through the EXE, doesn't even run the code.

@vysecurity do still have the same issue if you use the -loader control or any other loaders?

**Comment by Tylous** [comment]
I've pushed a small change could you please test out the binaries now and see if that fixes your issues @vysecurity  @kyleavery

**Comment by Tylous** [comment]
Update @kyleavery: First off thank you for sending me the shellcode to test that made a huge difference. So it looks like it has to do with how the shellcode is executed. In the binary mode, it uses syscall.syscall and treats the shellcode as byte array format as input. In the other loaders, it calls the pointer to the starting address point. I also tested this with the `-injection` flag, which is uses another different way of loading and executing shellcode, both in binary and other loader formats and it worked fine. Based on this I was able to drill down deeper and determine that is not an issue with donut shellcode size but a pointer issue. I suspect that when it's executed in a byte array format it causes a null pointer to dereference. To fix this I am gonna have to build a new binary loader template.  As a quick fix, I would suggest avoiding using donut shellcode in the vanilla binary mode, instead use any of the other loaders or use the `-injection` flag if you need binary. Those should work fine while I address this retooling bug.

**Comment by kyleavery** [comment]
Thanks for all your time looking into this! I really appreciate the effort 😃

**Comment by Tylous** [comment]
Hey @kyleavery Sorry for the delay, I just wanted to give you an update that I have fixed this issue with binary loaders and donut. 
![image](https://user-images.githubusercontent.com/15052743/135665932-57a65af2-a7bc-4246-b1c8-b7b5cc473dd7.png)
It's coming up with the next update which will be released shortly along with many other changes and new features.

**Comment by kyleavery** [comment]
Wow, awesome! Thanks again for all your hard work.

**Comment by Tylous** [comment]
Fixed in Patch 3.0
