### ISSUE TITLE
cmd.Run() failed with exit status 0xffffffff

### ISSUE THREAD

**Issue by qwertymamont** [optiv/ScareCrow#66]
Hello! After trying to compile it gives the following error: cmd.Run() failed with exit status 0xffffffff

What could be the problem?

**Comment by Tylous** [comment]
There is now run.cmd command when you compile the framework. If you are referring to making a loader then, it could be on the code cert. I would need to see the command you than and the output to help troubleshoot it.

**Comment by qoo7972365** [comment]
[*] Encrypting Shellcode Using AES Encryption
[+] Shellcode Encrypted
[+] Patched ETW Enabled
[+] Patched AMSI Enabled
[+] Sleep Timer set for 2520 milliseconds 
[*] Creating an Embedded Resource File
[+] Created Embedded Resource File With Outlook's Properties
[*] Compiling Payload
[+] Payload Compiled
[*] Signing Outlook.exe With a Fake Cert
2022/12/10 17:29:48 cmd.Run() failed with exit status 255

**Comment by vay3t** [comment]
I think that's where the problem lies: https://github.com/optiv/ScareCrow/blob/main/limelighter/limelighter.go#L139-L153
What operating system do you use? and its architecture?

**Comment by Tylous** [comment]
No, this is an issue with the latest version of osslsigncode. You need to revert to this version as its the latest that works. 
```osslsigncode 2.3.0, using:
	OpenSSL 1.1.1s  1 Nov 2022 (Library: OpenSSL 1.1.1s  1 Nov 2022)
	libcurl/7.79.1 SecureTransport (LibreSSL/3.3.5) zlib/1.2.11 nghttp2/1.45.1

Please send bug-reports to Michal.Trojnara@stunnel.org```

**Comment by jphillips241** [comment]
hi @Tylous. I am having a similar issue as the above mentioned cmd.Run() failed with exit status 255 when trying to compile.

I am a little confused by your response above because you mentioned it being an issue with osslsigncode and to revert to 'this' version and you instead show the version of OpenSSL 1.1.1s. 

So, I installed OpenSSL 1.1.1s and still have issues. For clarity can you list specifically which version of osslsigncode is needed?

Here is the output when I try to compile:

![Screenshot 2023-06-06 at 11 18 12 AM](https://github.com/optiv/ScareCrow/assets/20777201/0bad0e5c-58d9-40a7-8ffd-7626aebeae94)

And here are my versions of osslsigncode and OpenSSL I have installed:

![Screenshot 2023-06-06 at 11 19 33 AM](https://github.com/optiv/ScareCrow/assets/20777201/00beaa29-7632-4030-811b-f2fd017698ce)

I have also installed various versions of osslsigncode including the most recent and have had no luck. 

Sorry if I'm missing something obvious! Appreciate your time!
